image: devillex/docker-firebase

stages:
    - build
    - deploy

variables:

cache:
    paths:
        - node_modules/
    key: ${CI_COMMIT_REF_SLUG}

buildGatsby:
    stage: build
    script:
        - npm install --unsafe-perm
        - ./node_modules/.bin/gatsby build --prefix-paths
    artifacts:
        paths:
            - public
    only:
        - master

deployFirebase:
    stage: deploy
    only:
        - master
    script:
        - firebase use najetru --token $FIREBASE_TOKEN
        - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
